### ISSUE TITLE
Lab 2.6: Loading Images using TestCLI: Base 64

### ISSUE THREAD

**Issue by captainquirky** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#24]
I've followed and double checked I've followed all instructions in labs:  when running **_dotnet run -- -process <%GitHubDir%>\AI-100-Design-Implement-Azure-AISol\Lab2-Implement_Computer_Vision\sample_images_**

I get the following error

Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.)) ---> System.AggregateException: One or more errors occurred. (The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.) ---> System.FormatException: The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.
   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at Microsoft.Azure.Cosmos.DocumentClient..ctor(Uri serviceEndpoint, String authKeyOrResourceToken, EventHandler`1 sendingRequestEventArgs, ConnectionPolicy connectionPolicy, Nullable`1 desiredConsistencyLevel, JsonSerializerSettings serializerSettings, ApiType apitype, EventHandler`1 receivedResponseEventArgs, HttpMessageHandler handler, ISessionContainer sessionContainer, Nullable`1 enableCpuMonitor, Func`2 transportClientHandlerFactory, IStoreClientFactory storeClientFactory)
   at Microsoft.Azure.Cosmos.CosmosClient..ctor(String accountEndpoint, String authKeyOrResourceToken, CosmosClientOptions clientOptions)
   at Microsoft.Azure.Cosmos.Fluent.CosmosClientBuilder.Build()
   at ImageStorageLibrary.CosmosDBHelper`1.BuildAsync() in C:\GitHub\AI-100-Design-Implement-Azure-AISol\Lab2-Implement_Computer_Vision\code\Starter\ImageStorageLibrary\CosmosDBHelper.cs:line 60
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at ImageStorageLibrary.CosmosDBHelper`1.get_GetInstance() in C:\GitHub\AI-100-Design-Implement-Azure-AISol\Lab2-Implement_Computer_Vision\code\Starter\ImageStorageLibrary\CosmosDBHelper.cs:line 36
   at TestCLI.Program.InitializeAsync(String settingsFile) in C:\GitHub\AI-100-Design-Implement-Azure-AISol\Lab2-Implement_Computer_Vision\code\Starter\TestCLI\Program.cs:line 82
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at TestCLI.Program.<>c__DisplayClass0_0.<Main>b__0() in C:\GitHub\AI-100-Design-Implement-Azure-AISol\Lab2-Implement_Computer_Vision\code\Starter\TestCLI\Program.cs:line 34
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at TestCLI.Program.Main(String[] args) in C:\GitHub\AI-100-Design-Implement-Azure-AISol\Lab2-Implement_Computer_Vision\code\Starter\TestCLI\Program.cs:line 54

**Comment by gerryaobrien** [comment]
The labs were not initially designed to support dotnet core.   Future updates will address this.  You will need to use the full version of Visual Studio on a Windows PC or use the hosted environment that was set up for these labs, as part of the AI-100 instructor-led course.
