### ISSUE TITLE
Lab 2.6

### ISSUE THREAD

**Issue by nilkantjagtap** [MicrosoftLearning/AI-100-Design-Implement-Azure-AISol#43]
Loading Images Using TestCLI : showing following error
-----------------------------------------------------------------
D:\AI100\Lab2-Implement_Computer_Vision\code\Finished\TestCLI>dotnet run -process D:\AI100\Lab2-Implement_Computer_Vision\sample_images
Processing Directory D:\AI100\Lab2-Implement_Computer_Vision\sample_images
Processing D:\AI100\Lab2-Implement_Computer_Vision\sample_images\Analysis_1.jpg
Error: Microsoft.ProjectOxford.Vision.ClientException: Exception of type 'Microsoft.ProjectOxford.Vision.ClientException' was thrown.
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.HandleException(Exception exception)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.<SendAsync>b__42_1[TRequest,TResponse](Exception e)
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.SendAsync[TRequest,TResponse](String method, TRequest requestBody, WebRequest request, Action`1 setHeadersCallback)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.AnalyzeImageAsync[T](T body, IEnumerable`1 visualFeatures, IEnumerable`1 details)
   at Microsoft.ProjectOxford.Vision.VisionServiceClient.AnalyzeImageAsync(Stream imageStream, IEnumerable`1 visualFeatures, IEnumerable`1 details)
   at ServiceHelpers.VisionServiceHelper.<>c__DisplayClass21_0.<<AnalyzeImageAsync>b__0>d.MoveNext() in D:\AI100\Lab2-Implement_Computer_Vision\code\Finished\ProcessingLibrary\ServiceHelpers\VisionServiceHelper.cs:line 118
--- End of stack trace from previous location where exception was thrown ---
   at ServiceHelpers.VisionServiceHelper.RunTaskWithAutoRetryOnQuotaLimitExceededError[TResponse](Func`1 action) in D:\AI100\Lab2-Implement_Computer_Vision\code\Finished\ProcessingLibrary\ServiceHelpers\VisionServiceHelper.cs:line 79
   at ServiceHelpers.VisionServiceHelper.AnalyzeImageAsync(Func`1 imageStreamCallback, IEnumerable`1 visualFeatures, IEnumerable`1 details) in D:\AI100\Lab2-Implement_Computer_Vision\code\Finished\ProcessingLibrary\ServiceHelpers\VisionServiceHelper.cs:line 118
   at ProcessingLibrary.ImageProcessor.ProcessImageAsync(Func`1 imageStreamCallback, String imageId) in D:\AI100\Lab2-Implement_Computer_Vision\code\Finished\ProcessingLibrary\ImageProcessor.cs:line 25
   at TestCLI.Program.ProcessDirectoryAsync(String dir, Boolean forceUpdate) in D:\AI100\Lab2-Implement_Computer_Vision\code\Finished\TestCLI\Program.cs:line 112

**Comment by houbena** [comment]
Same here

**Comment by houbena** [comment]
The fix is in the instructions:
Note the url for cognitive services should end with /vision/v1.0 for the project oxford apis. For example https://westus2.api.cognitive.microsoft.com/vision/v1.0.
